# https://www.composerize.com/
name: feathertracker
services:
    azure-sql-edge:
        cap_add:
            - SYS_PTRACE
        environment:
            - ACCEPT_EULA=1
            - MSSQL_SA_PASSWORD=yourStrong(!)Password
        ports:
            - 6028:1433
        container_name: feathertracker-sql-server
        image: mcr.microsoft.com/azure-sql-edge
        volumes:
            - feathertracker-azure-sql:/var/opt/mssql
volumes:
    feathertracker-azure-sql:
        name: feathertracker-azure-sql