name: docker-feathertracker
services:
    docker-feathertracker-api:
        container_name: docker-feathertracker-api
        environment:
            - JWT_LIFETIME=120
            - DB_PASSWORD=yourStrong(!)Password
        ports:
            - 63098:8080
        hostname: docker-feathertracker-api
        image: kris701/feathertracker-api
        volumes:
            - docker-feathertracker-api:/api/.secrets
        networks:
          - back-end
          - front-end
        restart: unless-stopped

    docker-feathertracker-frontend:
        container_name: docker-feathertracker-frontend
        ports: 
          - 52905:8080
        image: kris701/feathertracker-frontend
        networks:
          - front-end
        restart: unless-stopped

    docker-feathertracker-database:
        cap_add:
            - SYS_PTRACE
        environment:
            - MSSQL_SA_PASSWORD=yourStrong(!)Password
        # Uncomment this if you need direct access to the database
        #ports: 
        #    - 46034:1433
        container_name: docker-feathertracker-database
        hostname: docker-feathertracker-database
        image: kris701/feathertracker-database
        volumes:
            - docker-feathertracker-database:/var/opt/mssql
        command:
          /bin/bash -c "/databaseinit/databaseinit.sh"
        networks:
          - back-end
        restart: unless-stopped
volumes:
    docker-feathertracker-database:
        name: docker-feathertracker-database
    docker-feathertracker-api:
        name: docker-feathertracker-api

networks:
  front-end:
  back-end: