CREATE PROCEDURE [BRD].[SP_AddBird]
	@ExecID UNIQUEIDENTIFIER,
	@Name NVARCHAR(MAX),
	@Description NVARCHAR(MAX),
	@Type NVARCHAR(MAX),
	@Icon NVARCHAR(MAX),
	@BirthDate DATETIME,
	@UserID UNIQUEIDENTIFIER
AS
BEGIN TRANSACTION
	DECLARE @ID UNIQUEIDENTIFIER = NEWID()
	INSERT INTO [BRD].[Birds] VALUES (@ID, @Name, @Description, @Type, @Icon, @UserID, @BirthDate, GETUTCDATE(), NULL);
	EXEC [BRD].[SP_GetBird] @ExecID, @ID
COMMIT