CREATE PROCEDURE [BRD].[SP_DeleteBird]
	@ExecID UNIQUEIDENTIFIER,
	@ID UNIQUEIDENTIFIER
AS
BEGIN TRANSACTION
	DELETE FROM [BRD].[BirdWeights] WHERE FK_BirdID = @ID;
	DELETE FROM [BRD].[Birds] WHERE PK_ID = @ID;
COMMIT