CREATE PROCEDURE [COR].[SP_RegisterUser]
	@FirstName NVARCHAR(MAX),
	@LastName NVARCHAR(MAX),
	@LoginName NVARCHAR(100),
	@Password NVARCHAR(MAX)
AS
BEGIN TRANSACTION
	DECLARE @ID UNIQUEIDENTIFIER = NEWID()
	INSERT INTO [COR].[Users] VALUES (@ID, @FirstName, @LastName, @LoginName, @Password, 1, 0, GETUTCDATE(), NULL);
	INSERT INTO [COR].[UserPermissions] SELECT NEWID(), @ID, PK_ID FROM [COR].[Permissions] WHERE IsStaff = 0;
	EXEC [COR].[SP_GetUser] @ID, @ID
COMMIT