CREATE PROCEDURE [FOD].[AddRecipie]
@Name NVARCHAR (MAX), @Recipie NVARCHAR (MAX), @Quantity DECIMAL (18, 3), @Unit NVARCHAR (MAX)
AS
BEGIN TRANSACTION;

DECLARE @ID AS UNIQUEIDENTIFIER = NEWID();

INSERT  INTO [FOD].[Recipies]
VALUES (@ID, @Name, @Recipie, @Quantity, @Unit, GETUTCDATE(), NULL);

EXECUTE [FOD].[GetRecipie] @ID;

COMMIT TRANSACTION;