CREATE PROCEDURE [FOD].[DeleteRecipie]
@ID UNIQUEIDENTIFIER
AS
BEGIN TRANSACTION;

DELETE [FOD].[RecipieBirds]
WHERE  FK_RecipieID = @ID;

DELETE [FOD].[Recipies]
WHERE  ID = @ID;

COMMIT TRANSACTION;