CREATE TABLE [BRD].[BirdWeights]
(
	[PK_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Grams] INT NOT NULL,
	[FK_BirdID] UNIQUEIDENTIFIER NOT NULL,
	[Timestamp] DATETIME NOT NULL

	CONSTRAINT [FK_Weights_Birds] FOREIGN KEY ([FK_BirdID]) REFERENCES [BRD].[Birds]([PK_ID]) ON DELETE CASCADE
)