CREATE TABLE [BRD].[Birds]
(
	[PK_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(MAX) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[Type] NVARCHAR(MAX) NOT NULL,
	[Icon] NVARCHAR(MAX) NOT NULL,
	[FK_UserID] UNIQUEIDENTIFIER NOT NULL,
	[BirthDate] DATETIME NOT NULL,

	[CreatedAt] DATETIME NOT NULL,
	[UpdatedAt] DATETIME NULL

	CONSTRAINT [FK_Birds_Users] FOREIGN KEY ([FK_UserID]) REFERENCES [COR].[Users]([PK_ID]) ON DELETE CASCADE
)