CREATE TABLE [BUR].[BugReports]
(
	[PK_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,

	[Title] NVARCHAR(MAX) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[IsResolved] BIT NOT NULL,
	[FK_CreatedBy_ID] UNIQUEIDENTIFIER NULL,

	[CreatedAt] DATETIME NOT NULL,
	[UpdatedAt] DATETIME NULL

	CONSTRAINT [FK_BugReports_Users] FOREIGN KEY ([FK_CreatedBy_ID]) REFERENCES [COR].[Users]([PK_ID]) ON DELETE SET NULL
)