CREATE TABLE [FOD].[RecipieBirds] (
    [ID]           UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [FK_RecipieID] UNIQUEIDENTIFIER NOT NULL,
    [FK_BirdID]    UNIQUEIDENTIFIER NOT NULL CONSTRAINT [FK_RecipieBirds_Birds] FOREIGN KEY ([FK_BirdID]) REFERENCES [COR].[Birds] ([ID]) ON DELETE CASCADE CONSTRAINT [FK_RecipieBirds_Recipies] FOREIGN KEY ([FK_RecipieID]) REFERENCES [FOD].[Recipies] ([ID]) ON DELETE CASCADE
);