CREATE PROCEDURE [COR].[AddBird]
@Name NVARCHAR (MAX), @Description NVARCHAR (MAX), @Type NVARCHAR (MAX), @Icon NVARCHAR (MAX), @BirthDate DATETIME
AS
BEGIN TRANSACTION;

DECLARE @ID AS UNIQUEIDENTIFIER = NEWID();

INSERT  INTO [COR].[Birds]
VALUES (@ID, @Name, @Description, @Type, @Icon, @BirthDate, GETUTCDATE(), NULL);

EXECUTE [COR].[GetBird] @ID;

COMMIT TRANSACTION;