CREATE PROCEDURE [BRD].[SP_PurgeBirdWeights]
	@ExecID UNIQUEIDENTIFIER,
	@IDs [GLB].[GuidListType] READONLY
AS
BEGIN TRANSACTION
	DELETE FROM [BRD].[BirdWeights] WHERE PK_ID IN (SELECT * FROM @IDs);
COMMIT