CREATE PROCEDURE [WGT].[AddWeight]
@Grams INT, @BirdID UNIQUEIDENTIFIER, @Timestamp DATETIME
AS
BEGIN TRANSACTION;

DECLARE @ID AS UNIQUEIDENTIFIER = NEWID();

INSERT  INTO [WGT].[Weights]
VALUES (@ID, @Grams, @BirdID, @Timestamp);

COMMIT TRANSACTION;