CREATE PROCEDURE [WGT].[AddWeight]
@Grams INT, @BirdID UNIQUEIDENTIFIER, @Timestamp DATETIME
AS
BEGIN TRANSACTION;

DECLARE @ID AS UNIQUEIDENTIFIER = NEWID();

INSERT  INTO [WGT].[Weight]
VALUES (@ID, @Grams, @BirdID, @Timestamp);

EXECUTE [WGT].[GetWeight] @ID;

COMMIT TRANSACTION;